CREATE DATABASE IF NOT EXISTS opta_monitor;
USE opta_monitor;

CREATE TABLE inputs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    i1 TINYINT(1) NOT NULL DEFAULT 0,
    i2 TINYINT(1) NOT NULL DEFAULT 0,
    i3 TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
